apiVersion: v1
data:
  repositories.yaml: |
    apiVersion: ""
    generated: "0001-01-01T00:00:00Z"
    repositories:
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: gojektech-incubator
      password: ""
      url: https://charts.gojek.tech/incubator/
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: stable
      password: ""
      url: https://kubernetes-charts.storage.googleapis.com
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: gojek-incubator
      password: ""
      url: http://chartmuseum.golabs.io/incubator
      username: ""
    - caFile: ""
      certFile: ""
      keyFile: ""
      name: bitnami
      password: ""
      url: https://charts.bitnami.com/bitnami
      username: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: repositories
  namespace: hermes
