required = [
  "github.com/golang/protobuf/protoc-gen-go"
]

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1643683e1b54a9e88ad26d98f81400c8c9d9f4f9"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.1"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "4.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/technosophos/moniker"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~6.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.9.2"

[prune]
  go-tests = true
  unused-packages = true
