ignored = ["k8s.io/client-go","k8s.io/apimachinery","k8s.io/apiserver","k8s.io/metrics"]

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "~2.13.0"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "^4.0.0"

[[constraint]]
  name = "github.com/evanphx/json-patch"

[[constraint]]
  name = "github.com/ghodss/yaml"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "^0.2.1"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/technosophos/moniker"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.2.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.7.0"
