version: 2
jobs:
  build:
    working_directory: /go/src/k8s.io/helm
    parallelism: 3
    docker:
      - image: golang:1.12.1
    environment:
      PROJECT_NAME: "kubernetes-helm"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - gomod-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
            - gomod- # used as a fall through if the checksum fails to find exact entry
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: gomod-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod  # Where the package cache is stored
      - run:
          name: test
          command: .circleci/test.sh
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
