version: 2
jobs:
  build:
    working_directory: /go/src/k8s.io/helm
    parallelism: 3
    docker:
      - image: golang:1.10
    environment:
      PROJECT_NAME: "kubernetes-helm"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - restore_cache:
          keys:
            - dep-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
            - dep- # used as a fall through if the checksum fails to find exact entry
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: dep-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/pkg/dep  # Where the dep cache is stored
      - run:
          name: test
          command: .circleci/test.sh
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
