# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  frontend_deployment:
     repository: gcr.io/google-samples/gb-frontend
     tag: v4
  redis_master:
     repository: gcr.io/google_containers/redis
     tag: e2e
  redis_slave:
     repository: gcr.io/google_samples/gb-redisslave
     tag: v1
  pullPolicy: IfNotPresent
service:
  frontend:
    type: LoadBalancer
    port: 80
    selector:
      app: guestbook
      tier: frontend
  redis_master:
    port: 6379
    targetPort: 6379  
    selector:
      app: redis
      role: master
      tier: backend
  redis_slave:
    port: 6379
    selector:
      app: redis
      role: slave
      tier: backend
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
