# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Questions
description: I want to ask a question.
title: "Title"
labels:
  - question/support

body:
  - type: markdown
    attributes:
      value: |
        Please read the document carefully. Thanks!
        https://helm.sh/docs/

  - type: textarea
    id: ask
    attributes:
      label: "What do you want to ask?"
      description: "Please describe the details of your questions."
    validations:
      required: true
