name: build-test
on:
  push:
    branches:
      - 'main'
      - 'release-**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4.1.3
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin@5.0.0
        with:
          go-version: '1.21'
      - name: Test source headers are present
        run: make test-source-headers
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build
