name: release
on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
      AZURE_STORAGE_CONTAINER_NAME: "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Set Version
        run: |
          echo "::set-output name=VERSION::${GITHUB_REF##*/}"

      - name: Build Helm Binaries
        run: |
          make build-cross
          make dist checksum VERSION="${VERSION}"

      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s _dist/ -d "$AZURE_STORAGE_CONTAINER_NAME" --pattern 'helm-*' --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
